author: Borgdude
description: "Simple Paintball"
main: com.borgdude.paintball.Main
name: Simple_PaintBall
version: "${project.version}"
api-version: 1.13
softdepend: [Vault, Multiverse-Core]

commands:
  gun:
    description: Gives paintball gun
    usage: /<command>
  pb:
    description: Commands
    usage: /<command> <options> | /pb help - more info

permissions:
  paintball.admin:
    default: op
    description: admin commands
  paintball.gun.*:
    default: true
    description: Permissions for specific guns